version: 4.0.0.{build}
image: Visual Studio 2022
environment:
  push_to_nuget: true
nuget:
  project_feed: true
before_build:
- cmd: nuget restore Npoi.Mapper\Npoi.Mapper.sln
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: MyNupkg
configuration: Debug

# here we are going to override common configuration
for:

# configuration for "master" branch
# build in Release mode and deploy to NuGet
-
  branches:
    only:
      - master
  configuration: Release
  deploy:
    provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: 44c2feCrGZ8Dp5moFsAiH+oihZ8F2vR/yCHX46UgFmRNh++M5pegZAKweBD3MiVS
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: MyNupkg
    on:
      push_to_nuget: true
